name: Mix sad

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install gdown

      - name: Check FFmpeg
        run: |
          ffmpeg -version

      - name: Download audio from Google Drive
        run: |
          gdown "https://drive.google.com/uc?id=1mYrzVTc3DrIRQxXt1fI1ljEB_HictEf2" -O audio.mp3

      - name: Stream
        run: |
          ffmpeg -re -stream_loop -1 -i "audio.mp3" \
            -vn \
            -af "volume=2,aresample=async=1" \
            -c:a aac \
            -b:a 192k \
            -ar 44100 \
            -ac 2 \
            -flush_packets 0 \
            -f flv "rtmps://dc4-1.rtmp.t.me/s/2599776082:EhXvPrErk4Py95iXkP7rgw"

      - name: Done
        run: |
          echo "Finished."
